<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DTOs\GroceryItemDto.cs~RFb1588df.TMP" />
    <None Remove="Models\vtwlso4u.2d0~" />
  </ItemGroup>

</Project>
